### ISSUE TITLE
Directly link to execution API page

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan-book#12]
We should directly link to https://otterscan.github.io/execution-apis/api-documentation/ to save users from having to find the link on the GitHub page first.

**Comment by wmitsuda** [comment]
do you mean replace it in this page? https://docs.otterscan.io/api-docs/

**Comment by sealer3** [comment]
Yes, we should link to it directly from that page. You can decide whether it should replace the other link or not - I'm indifferent to that.
