### ISSUE TITLE
API spec FAQ page

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan-book#16]
It's not clear to me what [the FAQ page](https://docs.otterscan.io/api-docs/faq) is trying to say. For instance, I don't know what some examples of _Some Product XXX_ could be.

I think we should remove this FAQ page entirely and just add a few sentences to the parent "API Spec" page directly describing the design goals.

**Comment by wmitsuda** [comment]
I actually didn't want to name specific products, but I meant other external indexers projects

**Comment by sealer3** [comment]
Yes, I mean I didn't know it was referring to external indexers on the first read. I'll propose a change and we can discuss it some more.

**Comment by wmitsuda** [comment]
sure, pls, let me know if the wording is too strong or vague
